### PR TITLE
feat(Header): introduce check in typeahead cache before navigating

### PR DESCRIPTION
**Pull request by Napokue**
As discussed in #53 a possible way to prevent a user to navigate to a collection log that does not exist.

### CODE REVIEW

**Review by evansloan — CHANGES_REQUESTED** [review]
With this change it is not possible to search for shorter names. I did a lookup and there are several 2-3 character names. 'ie' is an example. Maybe only perform the check if the typeahead is populated? Obviously that still opens the possibility for searching non-existent accounts. If you have other ideas I'm all ears.

**Comment by Napokue** [comment]
Thank you for pointing that out.

It was a little too ambitious of me to think that such a naïve implementation would suffice. I have revisited it and also used your feedback to come up with another, more complex solution that will solve the issue and even minimize the API requests more.

What I did come up with was to introduce the following:
* Introduce a debounce to reduce the amount of calls to the search main logic and thus reducing the amount of maximum API requests per second to 4 per user.
* Spaces will not trigger the typeahead. Currently in production typing 2 or more characters will result in an API request that returns an Internal Server error.
* Search API will now trigger at a minimum of two characters. I have searched in the website and there are no 1 character usernames (correct me if I am wrong).
* Search API will only trigger if one of the two conditions are met:
1) An API request made has not been made yet, and the typeahead cache is empty.
2) The user pressed backspace and the current search length is now smaller than it was when the previous API request has been made. This is an optimization as a user now can start their search with: `Test`, which will send an API request and after that continue their search with: `Test User` without sending a new API request. If the user now decides to search for `Test account` it will still not send an API request, only when the user presses backspace and the new search will be `Tes` for instance.

Please let me know what you think of this implementation and if it is something we want.

**Review by evansloan — CHANGES_REQUESTED** [review]
I like the implementation, the typeahead feels a lot more responsive with these changes. I just had a couple things I wanted to bring up.

1. One character name search - Should probably fix

There is one name currently that this will be an issue for, their name is '1'. While they don't appear to be super active (last update was 2023-02-23), I don't want to restrict future users from accessing their logs.

2. Typeahead cache doesn't reset if selecting all characters in search box and immediately typing a new username

This one isn't as big of a deal, but since immediately typing after using Ctrl/Cmd+A or selecting all text in the input doesn't register a search length of 0, the typeahead cache will not get reset to it's init state. The new username typed will be checked against the previous values stored in the typeahead cache, which will result in an empty typeahead if the first 2 characters aren't identical. I'd be comfortable merging out without this fixed.

**Comment by Napokue** [comment]
Great, thanks for pointing out those two points.

> One character name search - Should probably fix
Agreed, I was not aware of one character users. Only checked a-z. Will do a little testing for this, but should not be a problem to change.

> Typeahead cache doesn't reset if selecting all characters in search box and immediately typing a new username
Good point! I have not considered that usecase. Is not too hard to fix, we could probably implement a check that checks if the first character of the "new" search query is equal to the first character of the old search query.

**Comment by Napokue** [comment]
After coming back after a couple of days I was able to view this issue from another perspective and simplified my initial rather complex proposal with a much (in my opinion) better implementation.

- Using CTRL + A and immediately typing characters will refresh the cache now.
- Search API request will trigger now at 1 character.
- All other earlier discussed points are also resolved and working.

I also took the time to optimize the `filterTypeahead` function, it will not filter through the whole cache now to only get the first 5 results. Worst case scenario, it will iterate through the whole cache if the last 5 elements are matching the filter.

**Review by evansloan — APPROVED** [review]

**Pull request merged**
